# for any settings we have this class
sql: true
services:
  github:
    name: 'Github'
    implementation: 'github'
  bitbucket:
    name: 'BitBucket'
    implementation: 'bitbucket'
  rubygems:
    name: 'RubyGems'
    implementation: 'rubygems'
  cloudfare:
    name: 'Cloudfare'
    implementation: 'cloudfare'
  facebook:
    name: 'Facebook'
    options:
      host: 'facebook.com'
  bash:
    name: 'Bash.im'
    options:
      host: 'bash.im'
  somehosts:
    name: 'Somehosts'
    options:
      host: ['bitbucket.org', 'id.atlassian.com', 'medium.com', 'elixir-lang.org']
      policy: 'all'
  always_down:
    name: 'Always Down'
    implementation: 'always_down'
